### ISSUE TITLE
Browser test

### ISSUE THREAD

**Issue by TrentWalton** [raygunray/thesignsofaustin.com#2]
- [x] Safari
- [x] Firefox
- [x] iOS
- [x] Android
- [x] Edge
- [x] IE 11, 10
- [x] Chrome

**Comment by TrentWalton** [comment]
Flexbox display for the signs and header are the only funny things for IE 10, but I bet you care as much as I do ;)

http://caniuse.com/#search=flexbox

**Comment by raygunray** [comment]
https://media.giphy.com/media/13NUIf3JyBLZ72/giphy.gif
